# Generated by Django 4.2.6 on 2023-11-01 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Residential', help_text='Project purpose', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(help_text='Enter a brief description of the project', max_length=1000)),
                ('location', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('Not started', 'Not started'), ('Inprogess', 'Inprogress'), ('Completed', 'Completed')], default='Not started', help_text='Project work status', max_length=50)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a product feature (e.g. Swimming-pool CCTV Solar-power)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projphoto', to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='facilities',
            field=models.ManyToManyField(help_text='Select a feature for this project', to='projects.projectfacility'),
        ),
    ]
