# Generated by Django 4.2.6 on 2023-11-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=True, upload_to='images/'),
        ),
    ]
