# Generated by Django 4.2.6 on 2023-11-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_image_product_featured_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdPhoto',
            new_name='ProductPhoto',
        ),
    ]
